# Scripts {#capitulo-script}
<!-- # Scripts {.tabset .tabset-fade .tabset-pills} -->

A continuación se muestran los scripts completos (lo mismo que se ha ido desglosando en las secciones anteriores, pero todo en conjunto)

## Cargas preliminares

```{r, eval=FALSE}
setwd("G:/SERNAC") # reemplazar por la ruta propia
install.packages("SERNAC_0.11.0.zip", repos = NULL, type = "win.binary")
install.packages("data.table")
install.packages("readxl")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("DT")
install.packages("plotly")
```

## Homologación de la base de datos {#homologacion}

```{r, eval=FALSE}
rm(list=ls())
library(SERNAC)
load("./DATA/dbf_v03.RData") # modificar por la ruta propia y el archivo apropiado

#-- Datos de homologacion
diccionario_columnas <- "DATA/homologacion_columnas.xlsx"
codigos_comunales <- "DATA/codigos_comunales.xlsx"
arbol_motivo_legal <- "DATA/arbol_de_mercado.xlsx"
datos_sii <- "DATA/SII/compilado_2018.csv"

#-- Datos nuevos
db1 <- "DATA/2019/B_Reclamos_al_31122019_extraida_24022020_liviana.csv"
# db2 <- "DATA/2020/BD 2020 al 01062020.csv"
# db2 <- "DATA/2020/B_Reclamos_al_15032020_extraida_16032020_amplia.csv"
# db2 <- "DATA/2020/B_Reclamos_al_31052020_extraida_02062020_amplia.csv"
db2 <- "DATA/2020/B_Reclamos_al_15062020_extraida_16062020_amplia.csv"

dbfM <- agregar_dbs(base=dbf, 
                    diccionario_columnas=diccionario_columnas,
                    codigos_comunales=codigos_comunales,
                    arbol_motivo_legal=arbol_motivo_legal,
                    datos_sii=datos_sii,
                    db1, db2)
```


## Ejecución alertas

```{r, eval=FALSE}
Clases <- c(mercado="proveedor_mercado_nombre",
            industria="proveedor_mercado_categoria_nombre", # proveedor_mercado_nombre va antes
            proveedor="proveedor_rut",
            producto="mercado_tipo_producto_nombre")

?computar_reclamos  # despliega la ayuda de R.
outt <- computar_reclamos(dbfM[estado_caso_nombre=="CERRADO"],
                          byCategoria=c("cierre_corto", 
                                        "motivo_legal_descripcion"),
                          # "proveedor_mercado_nombre", 
                          # "proveedor_mercado_categoria_nombre", 
                          # "proveedor_rut"),
                          # "cut_region"),
                          byClase=Clases,
                          lags=c(1:6, 12, 24), 
                          cuantiles=c(.25, .75), # c(0, .25, .5, .75, 1), 
                          IQR=c(.25, .75),
                          coef=1.5,
                          n_min=50,
                          usar_tiempo=F,
                          rango_fechas = c("2016-01-01", NA) ) # caso_creacion_fecha
outt

topn <- 30
nmin <- 15
t_observado <- c("2020-04-15", "2020-05-15")

outt <- seleccionar_ranking(outt, topn=topn, nmin=nmin, t_observado=t_observado, tipo='N')
outt <- extraer_series(outt)
outt <- reportar(outt)

shinyPlot(outt)
```

## Exportar tablas

```{r eval=FALSE}
exportar(outt, que=c('ranking'), verbose=T)  # formato inglés

exportar(outt, que=c('ranking'), verbose=T,  # formato español
         sep=";", dec=",")
```